In [1]:

import numpy as np
import pandas as pd
from dataclass import Potential
from data_prepare import prepare_data

df = prepare_data()

filter_name = "全国"
filter_mask = (df["省份"]!="台湾")

# filter_name = "北京"
# filter_mask = (df["省份"].isin(["北京"]))

mask = filter_mask
pt_total = Potential(
    df.loc[mask, :], name="%s城市医院整体市场" % filter_name, savepath="./plots/%s/" % filter_name
)
mask = (df["医院类型"] == "公立医院") & filter_mask
pt_hp = Potential(
    df.loc[mask, :], name="%s等级医院" % filter_name, savepath="./plots/%s/" % filter_name
)
mask = (df["医院类型"] == "社区医院") & filter_mask
pt_cm = Potential(
    df.loc[mask, :], name="%s社区医院" % filter_name, savepath="./plots/%s/" % filter_name
)
mask = (df["销售状态"] == "有销量目标医院") & filter_mask
pt_total_hassale = Potential(
    df.loc[mask, :], name="%s有量城市医院整体市场" % filter_name, savepath="./plots/%s/" % filter_name
)
mask = (df["医院类型"] == "社区医院") & (df["销售状态"] == "有销量目标医院") & filter_mask
pt_cm_hassale = Potential(
    df.loc[mask, :], name="%s有量社区医院" % filter_name, savepath="./plots/%s/" % filter_name
)
mask = (df["医院类型"] == "公立医院") & (df["销售状态"] == "有销量目标医院") & filter_mask
pt_hp_hassale = Potential(
    df.loc[mask, :], name="%s有量等级医院" % filter_name, savepath="./plots/%s/" % filter_name
)

In [ ]:
# 不同医院类型潜力/指标/销售的占比饼图
pt_total.plot_share_pie(value="终端潜力值", index="医院类型")
pt_total.plot_share_pie(value="信立坦2021指标", index="医院类型")
pt_total.plot_share_pie(value="信立坦MAT销量", index="医院类型")

In [ ]:
# 不同省份，城市，Decile医院类型占比
pt_total.plot_pivot_stackedbar(value="终端潜力值", 
                               index="省份", 
                               column="医院类型", 
                               line_share="社区医院",
                               unit_index="百万", 
                               y1labelthreshold=10)
pt_total.plot_pivot_stackedbar(value="终端潜力值", 
                               index="城市", 
                               column="医院类型", 
                               line_share="社区医院",
                               top=30, 
                               unit_index="百万", 
                               y1labelthreshold=10)
# pt_total.plot_pivot_stackedbar(value="终端潜力值", 
#                                index="区县", 
#                                column="医院类型", 
#                                line_share="社区医院",
#                                unit_index="百万", 
#                                y1labelthreshold=5)
pt_total.plot_pivot_stackedbar(
    value="医院名称", index="潜力分位", column="医院类型", percentage=True, y1labelthreshold=0
)

In [ ]:
# 不同地区经理医院类型占比
pt_total.plot_pivot_stackedbar(value="终端潜力值", 
                               index="地区经理", 
                               column="医院类型", 
                               line_share="社区医院",
                               unit_index="百万", 
                               y1labelthreshold=10)

In [ ]:
# 社区医院不同省份/城市的潜力值
pt_cm.plot_contrib_barline(value="终端潜力值", index="省份", unit_index="百万") 
pt_cm.plot_contrib_barline(value="终端潜力值", index="城市", unit_index="百万", top=30) 
# pt_cm.plot_contrib_barline(value="终端潜力值", index="区县", unit_index="百万") 

In [ ]:
pt_cm.table_to_excel("医院名称", top=30)
pt_cm_hassale.table_to_excel("医院名称", top=30, sort_by="信立坦MAT销量(DOT)")

In [27]:
# 社区医院不同销售状态的家数和潜力值
pt_cm.plot_share_pie(value="终端潜力值", index="销售状态")
pt_cm.plot_share_pie(value="医院名称", index="销售状态")
pt_cm_hassale.plot_share_pie(value="终端潜力值", index="信立坦销售表现")
pt_cm_hassale.plot_share_pie(value="医院名称", index="信立坦销售表现")

                终端潜力值
销售状态                 
有销量目标医院  3.673886e+08
无销量目标医院  3.001883e+08
非目标医院    4.637925e+08
[0.32472911 0.26533181 0.40993908]
./plots/全国/全国社区医院不同销售状态终端潜力值占比饼图.png has been saved...
         医院名称
销售状态         
有销量目标医院  1517
无销量目标医院  2109
非目标医院    8127
[0.12907343 0.17944355 0.69148303]
./plots/全国/全国社区医院不同销售状态终端数量占比饼图.png has been saved...
                    终端潜力值
信立坦销售表现                  
信立坦份额>10%    2.705057e+07
信立坦份额5%-10%  5.702380e+07
信立坦份额1%-5%   1.016219e+08
信立坦份额<1%     1.816923e+08
[0.07362932 0.15521388 0.276606   0.4945508 ]
./plots/全国/全国有量社区医院不同信立坦销售表现终端潜力值占比饼图.png has been saved...
              医院名称
信立坦销售表现           
信立坦份额>10%    238.0
信立坦份额5%-10%  176.0
信立坦份额1%-5%   422.0
信立坦份额<1%     681.0
[0.1568886  0.11601846 0.27818062 0.44891233]
./plots/全国/全国有量社区医院不同信立坦销售表现终端数量占比饼图.png has been saved...


In [33]:
# 社区医院不同省份/城市下分销售状态的潜力值
pt_cm.plot_pivot_stackedbar(
    value="终端潜力值", index="省份", column="销售状态", percentage=True, y1labelthreshold=2
) 
pt_cm.plot_pivot_stackedbar(
    value="终端潜力值", index="城市", column="销售状态", top=30, percentage=True, y1labelthreshold=2
) 
# pt_cm.plot_pivot_stackedbar(
#     value="终端潜力值", index="区县", column="销售状态", percentage=True, y1labelthreshold=2
# ) 
pt_cm_hassale.plot_pivot_stackedbar(
    value="终端潜力值", index="省份", column="信立坦销售表现", percentage=True, y1labelthreshold=2
) 
pt_cm_hassale.plot_pivot_stackedbar(
    value="终端潜力值", index="城市", column="信立坦销售表现", top=30, percentage=True, y1labelthreshold=2
) 
# pt_cm_hassale.plot_pivot_stackedbar(
#     value="终端潜力值", index="区县", column="信立坦销售表现", percentage=True, y1labelthreshold=2
# ) 

          有销量目标医院       无销量目标医院         非目标医院
省份                                           
北京   9.135416e+07  8.271228e+07  1.010676e+07
江苏   5.061725e+07  8.646597e+07  3.871137e+07
浙江   5.443339e+07  5.861535e+07  4.454788e+07
上海   6.260439e+07  1.996594e+07  3.278366e+07
广东   6.283891e+06  1.739981e+07  3.419433e+07
天津   4.320587e+07  7.513492e+06  2.378275e+06
山东   2.194895e+07  9.513081e+06  1.929825e+07
福建   2.982626e+07  5.098431e+06  8.829915e+06
河北   4.093033e+05  1.746802e+06  3.816302e+07
四川   3.654904e+06  5.279035e+06  2.356229e+07
辽宁   0.000000e+00  0.000000e+00  2.683098e+07
黑龙江  0.000000e+00  0.000000e+00  2.659258e+07
内蒙古  0.000000e+00  0.000000e+00  2.174086e+07
湖南   1.978449e+05  5.245042e+04  1.966197e+07
山西   5.998898e+04  5.817721e+04  1.682638e+07
湖北   1.144965e+05  6.397540e+05  1.441911e+07
吉林   7.577797e+04  3.976509e+04  1.123265e+07
新疆   5.353304e+05  1.077293e+06  9.661605e+06
陕西   0.000000e+00  0.000000e+00  9.209427e+06
江西   1.928901e+05  0.000000e+00  8

In [34]:
# 社区医院不同潜力分位下的销售状态
pt_cm.plot_pivot_stackedbar(
    value="终端潜力值", index="潜力分位", column="销售状态", percentage=True, percentage_label=True
) 
# 社区医院不同潜力分位下的销售状态
pt_cm_hassale.plot_pivot_stackedbar(
    value="终端潜力值", index="潜力分位", column="信立坦销售表现", percentage=True, percentage_label=True
) 

           有销量目标医院       无销量目标医院         非目标医院
潜力分位                                          
10    3.425263e+06  0.000000e+00  0.000000e+00
9     2.664138e+07  8.959161e+06  0.000000e+00
8     4.682272e+07  3.456026e+07  0.000000e+00
7     4.815469e+07  2.628314e+07  3.560116e+06
6     8.749275e+07  4.688272e+07  2.550239e+07
5     5.206242e+07  3.722167e+07  1.640953e+07
4     4.234512e+07  4.429504e+07  4.961173e+07
3     2.799878e+07  4.102658e+07  1.044475e+08
2     2.592270e+07  5.005209e+07  1.531024e+08
1     6.522738e+06  1.090763e+07  1.111588e+08
./plots/全国/全国社区医院各潜力分位不同销售状态潜力DOT柱状图.png has been saved...
         信立坦份额>10%   信立坦份额5%-10%    信立坦份额1%-5%      信立坦份额<1%
潜力分位                                                        
10    0.000000e+00  0.000000e+00  0.000000e+00  3.425263e+06
9     0.000000e+00  2.363514e+06  3.198735e+06  2.107913e+07
8     1.274346e+06  6.888364e+06  1.744682e+07  2.121320e+07
7     7.653904e+05  1.242153e+07  1.993443e+07  1.503334e+07
6     2.293

In [26]:
# 数据汇总表
pt_cm.table_to_excel(index="省份")
pt_cm.table_to_excel(index="城市", top=30)
# pt_cm.table_to_excel(index="区县")
pt_cm.table_to_excel(index="潜力分位")
pt_cm_hassale.table_to_excel(index="医院名称", top=30)
pt_cm_hassale.table_to_excel(index="医院名称", top=30, sort_by="信立坦MAT销量(DOT)")

     终端数量       潜力(DOT)      潜力贡献  无销量目标医院终端数量  有销量目标医院终端数量  非目标医院终端数量  无销量目标医院潜力(DOT)  有销量目标医院潜力(DOT)  非目标医院潜力(DOT)  信立坦目标覆盖终端数量  信立坦目标覆盖潜力(DOT %)  信立坦销售覆盖终端数量  信立坦销售覆盖潜力(DOT %)  信立坦MAT销量(DOT)   信立坦销售贡献                                               销售代表  销售代表人数  信立坦所有终端份额  信立坦目标终端份额  信立坦销售终端份额  代表人均潜力覆盖(DOT)  代表人均销量(月均盒数)
省份                                                                                                                                                                                                                                                                                                                                  
北京   1266  1.841732e+08  0.162788          693          410        163    8.271228e+07    9.135416e+07  1.010676e+07         1103          0.945124          410          0.496016        3169201  0.222412  nan,王超-2,nan,吴媛芳,徐士博,池旭青,李华丽,nan,王志吉,王超-2,王志吉,...      26   0.017208   0.018207   0.034692   7.083585e+06   1451.099359
江苏   1010  1.757946e+08  

In [ ]:
# 终端潜力 vs 信立坦份额 气泡图
pt_cm.plot_2d_bubble(
    value_x="终端潜力值",
    value_y="信立坦销售份额",
    index="医院名称",
    log_x=False,
    log_y=False,
    z_scale=0.000001,
    label_limit=0,
    with_reg=False,
    fmt_y="{:.0%}",
    lim_y=[0, 1],
)


In [ ]:
# 不同省份/城市的潜力 vs 信立坦销量对比
pt_cm.plot_2d_bubble(
    value_x="终端潜力值",
    value_y="信立坦MAT销量",
    index="省份",
    log_x=True,
    log_y=True,
    z_scale=15,
    label_limit=100,
)

pt_cm.plot_2d_bubble(
    value_x="终端潜力值",
    value_y="信立坦MAT销量",
    index="城市",
    log_x=True,
    log_y=True,
    z_scale=15,
    top=30,
)


In [ ]:
# 不同省份/城市的潜力 vs 销售代表人数
pt_cm.plot_2d_bubble(
    value_x="终端潜力值", value_y="销售代表", index="省份", log_x=True, z_scale=15, label_limit=100
)
pt_cm.plot_2d_bubble(
    value_x="终端潜力值", value_y="销售代表", index="城市", log_x=True, z_scale=15, top=30
)

In [2]:
# 数据汇总表
pt_total.table_to_excel(index="省份")
pt_total.table_to_excel(index="城市")
pt_total.table_to_excel(index="事业部")
pt_total.table_to_excel(index="区域")
pt_total.table_to_excel(index="大区经理")
pt_total.table_to_excel(index="地区经理")
pt_total.table_to_excel(index="潜力分位")
pt_total.table_to_excel(index="医院名称")
pt_total_hassale.table_to_excel(index="医院名称", sort_by="信立坦MAT销量(DOT)")

     终端数量       潜力(DOT)      潜力贡献  无销量目标医院终端数量  有销量目标医院终端数量  非目标医院终端数量  无销量目标医院潜力(DOT)  有销量目标医院潜力(DOT)  非目标医院潜力(DOT)  信立坦目标覆盖终端数量  信立坦目标覆盖潜力(DOT %)  信立坦销售覆盖终端数量  信立坦销售覆盖潜力(DOT %)  信立坦MAT销量(DOT)   信立坦销售贡献                                               销售代表  销售代表人数  信立坦所有终端份额  信立坦目标终端份额  信立坦销售终端份额  代表人均潜力覆盖(DOT)  代表人均销量(月均盒数)
省份                                                                                                                                                                                                                                                                                                                                  
江苏   2577  5.189821e+08  0.115378          588          211       1778    1.880664e+08    1.865651e+08  1.443505e+08          799          0.721860          211          0.359480      5383868.0  0.044921  牟勇,蔡志君,nan,牟勇,刘畅,蒋震,王洁,nan,nan,夏季,nan,张静,黄秀荣,刘...      31   0.010374   0.014371   0.028858   1.674136e+07   2067.537634
广东   2662  4.629111e+08  