In [1]:
import numpy as np
import pandas as pd
from dataclass import Potential
from data_prepare import prepare_data

df = prepare_data()

filter_name = "全国"
filter_mask = (df["省份"]!="台湾")

# filter_name = "北京"
# filter_mask = (df["省份"].isin(["北京"]))

mask = filter_mask
pt_total = Potential(
    df.loc[mask, :], name="%s城市医院整体市场" % filter_name, savepath="./plots/%s/" % filter_name
)
mask = (df["医院类型"] == "公立医院") & filter_mask
pt_hp = Potential(
    df.loc[mask, :], name="%s等级医院" % filter_name, savepath="./plots/%s/" % filter_name
)
mask = (df["医院类型"] == "社区医院") & filter_mask
pt_cm = Potential(
    df.loc[mask, :], name="%s社区医院" % filter_name, savepath="./plots/%s/" % filter_name
)
mask = (df["销售状态"] == "有销量目标医院") & filter_mask
pt_total_hassale = Potential(
    df.loc[mask, :], name="%s有量城市医院整体市场" % filter_name, savepath="./plots/%s/" % filter_name
)
mask = (df["医院类型"] == "社区医院") & (df["销售状态"] == "有销量目标医院") & filter_mask
pt_cm_hassale = Potential(
    df.loc[mask, :], name="%s有量社区医院" % filter_name, savepath="./plots/%s/" % filter_name
)
mask = (df["医院类型"] == "公立医院") & (df["销售状态"] == "有销量目标医院") & filter_mask
pt_hp_hassale = Potential(
    df.loc[mask, :], name="%s有量等级医院" % filter_name, savepath="./plots/%s/" % filter_name
)

In [2]:
# 不同医院类型潜力/指标/销售的占比饼图
pt_total.plot_share_pie(value="终端潜力值", index="医院类型")
pt_total.plot_share_pie(value="信立坦年度指标", index="医院类型")
pt_total.plot_share_pie(value="信立坦MAT销量", index="医院类型")

             终端潜力值
医院类型              
公立医院  3.355973e+09
社区医院  1.157899e+09
[0.74347979 0.25652021]
./plots/全国/全国城市医院整体市场医院类型终端潜力值占比饼图.png has been saved...
        信立坦年度指标
医院类型           
公立医院  145514950
社区医院   28466599
[0.83638151 0.16361849]
./plots/全国/全国城市医院整体市场医院类型信立坦年度指标占比饼图.png has been saved...
         信立坦MAT销量
医院类型             
公立医院  108280410.7
社区医院   23353316.0
[0.82258866 0.17741134]
./plots/全国/全国城市医院整体市场医院类型信立坦MAT销量占比饼图.png has been saved...


In [5]:
# 不同省份，城市，Decile医院类型占比
pt_total.plot_pivot_stackedbar(value="终端潜力值", 
                               index="省份", 
                               column="医院类型", 
                               line_share="社区医院",
                               unit_index="百万", 
                               y1labelthreshold=10)
pt_total.plot_pivot_stackedbar(value="终端潜力值", 
                               index="城市", 
                               column="医院类型", 
                               line_share="社区医院",
                               top=30, 
                               unit_index="百万", 
                               y1labelthreshold=10)
# pt_total.plot_pivot_stackedbar(value="终端潜力值", 
#                                index="区县", 
#                                column="医院类型", 
#                                line_share="社区医院",
#                                unit_index="百万", 
#                                y1labelthreshold=5)
pt_total.plot_pivot_stackedbar(
    value="医院名称", index="等级+社区合并计算潜力分位", column="医院类型", percentage=True, y1labelthreshold=0
)

             公立医院          社区医院
省份                             
江苏   3.404927e+08  1.774211e+08
广东   4.044438e+08  5.969652e+07
北京   2.227988e+08  1.895780e+08
浙江   2.431005e+08  1.631943e+08
上海   2.292609e+08  1.169565e+08
山东   2.373392e+08  5.174674e+07
四川   1.365341e+08  3.421540e+07
福建   1.183780e+08  4.551305e+07
河北   1.024375e+08  4.067587e+07
河南   1.332035e+08  8.156176e+06
天津   7.742727e+07  5.571721e+07
湖北   1.158459e+08  1.533359e+07
辽宁   8.831513e+07  2.710951e+07
安徽   1.074671e+08  7.335767e+06
湖南   8.939261e+07  2.002070e+07
云南   8.974360e+07  7.570245e+06
江西   7.325962e+07  9.049641e+06
重庆   7.055529e+07  5.090627e+06
广西   6.615578e+07  6.461468e+06
新疆   5.961895e+07  1.139724e+07
黑龙江  4.327537e+07  2.676324e+07
山西   4.355403e+07  1.707290e+07
陕西   5.106511e+07  9.556564e+06
内蒙古  3.005246e+07  2.174086e+07
贵州   4.459752e+07  6.588841e+06
吉林   3.765854e+07  1.151896e+07
甘肃   3.978874e+07  5.434009e+06
宁夏   3.308418e+07  1.763629e+06
海南   1.860545e+07  2.160625e+06
青海   7.4

In [ ]:
# 不同地区经理医院类型占比
pt_total.plot_pivot_stackedbar(value="终端潜力值", 
                               index="地区经理", 
                               column="医院类型", 
                               line_share="社区医院",
                               unit_index="百万", 
                               y1labelthreshold=10)

In [ ]:
# 社区医院不同省份/城市的潜力值
pt_cm.plot_contrib_barline(value="终端潜力值", index="省份", unit_index="百万") 
pt_cm.plot_contrib_barline(value="终端潜力值", index="城市", unit_index="百万", top=30) 
# pt_cm.plot_contrib_barline(value="终端潜力值", index="区县", unit_index="百万") 

In [ ]:
# Excel综合报表
pt_cm.table_to_excel(
    lst_index=["省份", "城市", "社区医院内部潜力分位", "等级+社区合并计算潜力分位", "医院名称", "事业部", "区域", "大区经理", "地区经理"]
)

In [4]:
# 社区医院不同销售状态的家数和潜力值
pt_hp.plot_share_pie(value="终端潜力值", index="销售状态")
pt_hp.plot_share_pie(value="医院名称", index="销售状态")
pt_hp_hassale.plot_share_pie(value="终端潜力值", index="信立坦销售表现")
pt_hp_hassale.plot_share_pie(value="医院名称", index="信立坦销售表现")
pt_cm.plot_share_pie(value="终端潜力值", index="销售状态")
pt_cm.plot_share_pie(value="医院名称", index="销售状态")
pt_cm_hassale.plot_share_pie(value="终端潜力值", index="信立坦销售表现")
pt_cm_hassale.plot_share_pie(value="医院名称", index="信立坦销售表现")

                终端潜力值
销售状态                 
有销量目标医院  1.510407e+09
无销量目标医院  7.438642e+08
非目标医院    1.101702e+09
[0.45006522 0.22165382 0.32828096]
./plots/全国/全国等级医院销售状态终端潜力值占比饼图.png has been saved...
          医院名称
销售状态          
有销量目标医院   2219
无销量目标医院   2357
非目标医院    23005
[0.08045394 0.08545738 0.83408868]
./plots/全国/全国等级医院销售状态终端数量占比饼图.png has been saved...
                    终端潜力值
信立坦销售表现                  
信立坦份额>10%    3.555658e+08
信立坦份额5%-10%  3.615602e+08
信立坦份额1%-5%   3.931641e+08
信立坦份额<1%     4.001167e+08
[0.23541062 0.23937935 0.26030345 0.26490658]
./plots/全国/全国有量等级医院信立坦销售表现终端潜力值占比饼图.png has been saved...
              医院名称
信立坦销售表现           
信立坦份额>10%    649.0
信立坦份额5%-10%  336.0
信立坦份额1%-5%   557.0
信立坦份额<1%     677.0
[0.29247409 0.15141956 0.25101397 0.30509238]
./plots/全国/全国有量等级医院信立坦销售表现终端数量占比饼图.png has been saved...
                终端潜力值
销售状态                 
有销量目标医院  3.628416e+08
无销量目标医院  3.092105e+08
非目标医院    4.858473e+08
[0.31336194 0.26704437 0.41959369]
./plots/全国/全国社区医院销

In [5]:
# 社区医院不同省份/城市下分销售状态的潜力值
pt_cm.plot_pivot_stackedbar(
    value="终端潜力值", index="省份", column="销售状态", percentage=True, y1labelthreshold=2
) 
pt_cm.plot_pivot_stackedbar(
    value="终端潜力值", index="城市", column="销售状态", top=30, percentage=True, y1labelthreshold=2
) 
# pt_cm.plot_pivot_stackedbar(
#     value="终端潜力值", index="区县", column="销售状态", percentage=True, y1labelthreshold=2
# ) 
pt_cm_hassale.plot_2d_barline(value_bar="终端潜力值",value_line="信立坦MAT销量",index="省份", unit_index="百万")
pt_cm_hassale.plot_2d_barline(value_bar="终端潜力值",value_line="信立坦MAT销量",index="城市", top=30, unit_index="百万")
# pt_cm_hassale.plot_pivot_stackedbar(
#     value="终端潜力值", index="区县", column="信立坦销售表现", percentage=True, y1labelthreshold=2
# ) 

          有销量目标医院       无销量目标医院         非目标医院
省份                                           
北京   9.932368e+07  7.439538e+07  1.266998e+07
江苏   5.669286e+07  8.131870e+07  3.878665e+07
浙江   6.481378e+07  4.462278e+07  5.008702e+07
上海   5.080489e+06  7.837632e+07  3.267161e+07
广东   8.475798e+06  1.582844e+07  3.437735e+07
天津   4.465957e+07  6.114216e+06  2.378275e+06
山东   1.601956e+07  6.975492e+06  2.830207e+07
福建   3.054078e+07  4.505239e+06  8.846053e+06
河北   3.715615e+05  1.666262e+06  3.863590e+07
四川   4.549146e+06  4.591673e+06  2.430622e+07
辽宁   0.000000e+00  0.000000e+00  2.710951e+07
黑龙江  0.000000e+00  0.000000e+00  2.676324e+07
内蒙古  0.000000e+00  0.000000e+00  2.152294e+07
湖南   2.502953e+05  0.000000e+00  1.977041e+07
山西   5.998898e+04  5.817721e+04  1.695403e+07
湖北   1.605909e+05  5.936596e+05  1.456524e+07
吉林   7.577797e+04  0.000000e+00  1.144297e+07
新疆   8.356211e+05  7.770022e+05  9.770849e+06
陕西   0.000000e+00  0.000000e+00  9.556564e+06
江西   1.928901e+05  0.000000e+00  8

In [6]:
# 等级+社区医院不同潜力分位下的销售状态
pt_total.plot_pivot_stackedbar(
    value="终端潜力值", index="等级+社区合并计算潜力分位", column="销售状态", percentage=True, percentage_label=True
) 

# 社区医院不同潜力分位下的销售状态
pt_cm.plot_pivot_stackedbar(
    value="终端潜力值", index="等级+社区合并计算潜力分位", column="销售状态", percentage=True, percentage_label=True
) 
# 社区医院不同潜力分位下的销售状态
pt_cm_hassale.plot_2d_barline(value_bar="终端潜力值",value_line="信立坦MAT销量",index="等级+社区合并计算潜力分位", unit_index="百万")

                    有销量目标医院       无销量目标医院         非目标医院
等级+社区合并计算潜力分位                                          
10             3.699433e+08  7.023865e+07  1.177700e+07
9              3.594349e+08  7.912233e+07  1.258987e+07
8              3.291784e+08  1.034639e+08  1.842994e+07
7              2.621854e+08  1.435072e+08  4.604689e+07
6              1.870436e+08  1.855148e+08  7.882932e+07
5              1.474919e+08  1.688073e+08  1.349861e+08
4              9.456067e+07  1.345098e+08  2.221065e+08
3              6.158472e+07  8.370433e+07  3.060868e+08
2              4.518164e+07  6.159407e+07  3.446130e+08
1              1.664383e+07  2.261236e+07  4.120838e+08
./plots/全国/全国城市医院整体市场各潜力分位销售状态潜力DOT柱状图.png has been saved...
                    有销量目标医院       无销量目标医院         非目标医院
等级+社区合并计算潜力分位                                          
10             6.768498e+06  0.000000e+00  0.000000e+00
9              2.832663e+07  4.243488e+06  0.000000e+00
8              6.087550e+07  2.606759e+07  

In [2]:
# 终端潜力 vs 信立坦份额 气泡图
pt_cm_hassale.plot_2d_bubble(
    value_x="终端潜力值",
    value_y="信立坦销售份额",
    index="省份",
    log_x=False,
    log_y=False,
    z_scale=0.001,
    label_limit=50,
    with_reg=False,
    fmt_y="{:.0%}",
    lim_y=[0, 0.3],
    yavgline=True,
    xavgline=False,
)

pt_cm_hassale.plot_2d_bubble(
    value_x="终端潜力值",
    value_y="信立坦销售份额",
    index="城市",
    log_x=False,
    log_y=False,
    z_scale=0.001,
    label_limit=30,
    with_reg=False,
    fmt_y="{:.0%}",
    lim_y=[0, 0.3],
    yavgline=True,
    xavgline=False,
)


    终端数量       潜力(DOT)      潜力贡献  有销量目标医院终端数量  有销量目标医院潜力(DOT)  信立坦目标覆盖终端数量  信立坦目标覆盖潜力(DOT %)  信立坦销售覆盖终端数量  信立坦销售覆盖潜力(DOT %)  信立坦MAT销量(DOT)   信立坦销售贡献                                               销售代表  销售代表人数  信立坦所有终端份额  信立坦目标终端份额  信立坦销售终端份额  代表人均潜力覆盖(DOT)  代表人均销量(月均盒数)
省份                                                                                                                                                                                                                                                                           
北京   459  9.932368e+07  0.297000          459    9.932368e+07          459                 1          459          0.999986        4031972  0.209056  北京2-01-02 王超-2,北京2-01-03 吴媛芳,北京2-05-06 徐士博,北京2...      28   0.040594   0.040594   0.040595   3.547274e+06   1714.273810
浙江   171  6.481378e+07  0.193808          171    6.481378e+07          171                 1          171          0.999992        5282305  0.273886  浙江2-04-04 张定,浙江3-01-06 陈雪英,[],浙江3-03-02 

In [8]:
# 开户潜力占比 vs 信立坦份额 气泡图
pt_cm.plot_2d_bubble(
    value_x="终端潜力值",
    value_y="信立坦销售份额",
    index="省份",
    log_x=False,
    log_y=False,
    z_scale=0.00003,
    label_limit=50,
    with_reg=False,
    fmt_x="{:.0%}",
    fmt_y="{:.0%}",
    lim_y=[0, 0.2],
    xavgline=True,
    yavgline=True,
)

pt_cm.plot_2d_bubble(
    value_x="终端潜力值",
    value_y="信立坦销售份额",
    index="城市",
    log_x=False,
    log_y=False,
    z_scale=0.00003,
    label_limit=50,
    with_reg=False,
    fmt_x="{:.0%}",
    fmt_y="{:.0%}",
    lim_y=[0, 0.3],
    xavgline=True,
    yavgline=True,
)


     终端数量       潜力(DOT)      潜力贡献  无销量目标医院终端数量  有销量目标医院终端数量  非目标医院终端数量  无销量目标医院潜力(DOT)  有销量目标医院潜力(DOT)  非目标医院潜力(DOT)  信立坦目标覆盖终端数量  信立坦目标覆盖潜力(DOT %)  信立坦销售覆盖终端数量  信立坦销售覆盖潜力(DOT %)  信立坦MAT销量(DOT)   信立坦销售贡献                                               销售代表  销售代表人数  信立坦所有终端份额  信立坦目标终端份额  信立坦销售终端份额  代表人均潜力覆盖(DOT)  代表人均销量(月均盒数)
省份                                                                                                                                                                                                                                                                                                                                  
北京   1276  1.863890e+08  0.163087          639          459        178    7.439538e+07    9.932368e+07  1.266998e+07         1098          0.932025          459          0.532876        4031972  0.209056  nan,北京2-01-02 王超-2,nan,北京2-01-03 吴媛芳,北京2-05-06...      28   0.021632   0.023210   0.040595   6.656751e+06   1714.273810
江苏   1019  1.767982e+08  

In [ ]:
# 不同省份/城市的潜力 vs 信立坦销量对比
pt_cm.plot_2d_bubble(
    value_x="终端潜力值",
    value_y="信立坦MAT销量",
    index="省份",
    log_x=True,
    log_y=True,
    z_scale=15,
    label_limit=100,
)

pt_cm.plot_2d_bubble(
    value_x="终端潜力值",
    value_y="信立坦MAT销量",
    index="城市",
    log_x=True,
    log_y=True,
    z_scale=15,
    top=30,
)


In [ ]:
# 不同省份/城市的潜力 vs 销售代表人数
pt_cm.plot_2d_bubble(
    value_x="终端潜力值", value_y="销售代表", index="省份", log_x=True, z_scale=15, label_limit=100
)
pt_cm.plot_2d_bubble(
    value_x="终端潜力值", value_y="销售代表", index="城市", log_x=True, z_scale=15, top=30
)

In [7]:
# 数据汇总表
pt_total.table_to_excel(lst_index=["省份", "城市","潜力分位","医院名称","事业部","区域","大区经理","地区经理"])
pt_total_hassale.table_to_excel(index="医院名称", sort_by="信立坦MAT销量(DOT)")

     终端数量       潜力(DOT)      潜力贡献  无销量目标医院终端数量  有销量目标医院终端数量  非目标医院终端数量  无销量目标医院潜力(DOT)  有销量目标医院潜力(DOT)  非目标医院潜力(DOT)  信立坦目标覆盖终端数量  信立坦目标覆盖潜力(DOT %)  信立坦销售覆盖终端数量  信立坦销售覆盖潜力(DOT %)  信立坦MAT销量(DOT)   信立坦销售贡献                                               销售代表  销售代表人数  信立坦所有终端份额  信立坦目标终端份额  信立坦销售终端份额  代表人均潜力覆盖(DOT)  代表人均销量(月均盒数)
省份                                                                                                                                                                                                                                                                                                                                  
江苏   2571  5.179138e+08  0.114738          522          229       1820    1.802475e+08    1.909286e+08  1.467378e+08          751          0.716677          229          0.368647      6274597.0  0.047667  江苏1-04-05 牟勇,江苏1-04-08 蔡志君,[],江苏1-04-05 牟勇,江苏1...      38   0.012115   0.016905   0.032864   1.362931e+07   1965.725877
广东   2664  4.641403e+08  

KeyError: '潜力分位'